const colors={Groceries:'#16a193',Dining:'#b65673',Transport:'#4a85bd',Shopping:'#7657ad',Bills:'#b7892b',Other:'#7d8b92',Income:'#2d8b63',Transfer:'#7d8b92',All:'#08766e'};
const categories=[['Groceries','GR',589.12,32,14,'Whole Foods · Kroger · Costco',-4.8],['Dining','DI',387.45,21,18,'Restaurants · coffee · delivery',7],['Transport','TR',258.30,14,9,'Fuel · rideshare · parking',4.6],['Shopping','SH',202.68,11,7,'Target · Amazon · retail',-5.1],['Bills','BI',165.83,9,6,'Utilities · subscriptions',-.1],['Other','OT',239.18,13,11,'Health · personal · uncategorized',8.2]];
const tx=[['Today','Whole Foods','WF','Groceries','Chase Checking',-83.47,'spending','confirmed','8:12 AM'],['Today','Uber','UB','Transport','Chase Card',-24.18,'spending','review','7:36 AM'],['Today','Netflix','NF','Bills','Chase Card',-15.49,'spending','confirmed','6:18 AM'],['Yesterday','Payroll','PY','Income','Chase Checking',4260,'income','confirmed','5:42 PM'],['Yesterday','Shell','SH','Transport','Chase Card',-47.32,'spending','review','2:10 PM'],['Yesterday','Transfer to savings','TS','Transfer','Chase Checking',-800,'transfer','confirmed','9:05 AM'],['Jul 16','Target','TG','Shopping','Capital One',-54.28,'spending','confirmed','7:21 PM'],['Jul 16','Starbucks','SB','Dining','Chase Card',-6.75,'spending','confirmed','11:34 AM'],['Jul 15','Kroger','KR','Groceries','Chase Checking',-64.21,'spending','confirmed','6:03 PM'],['Jul 15','Card payment','CP','Transfer','Chase Checking',-400,'transfer','confirmed','1:16 PM'],['Jul 14','Amazon refund','AR','Shopping','Capital One',38.61,'spending','confirmed','3:28 PM'],['Jul 14','Unassigned merchant','?','Other','Chase Card',-19.42,'spending','review','8:14 AM']];
const reviewItems=[
{id:'r1',merchant:'Uber',initials:'UB',amount:-24.18,when:'Today · 7:36 AM',account:'Chase Card •• 4471',reason:'Category check',type:'category',question:'What kind of expense was this?',hint:'Transport is the strongest match, but you stay in control.',choices:[['Transport','TR','Rideshare or transit'],['Dining','DI','Food delivery'],['Other','OT','Something else']],selected:'Transport',remember:'Remember Uber as Transport for future alerts',evidence:'CHASE: $24.18 card purchase at UBER *TRIP. Card ending 4471.'},
{id:'r2',merchant:'Shell',initials:'SH',amount:-47.32,when:'Yesterday · 2:10 PM',account:'Chase Card •• 4471',reason:'Category check',type:'category',question:'How should Shell be categorized?',hint:'Fuel usually belongs in Transport. You can create a merchant default.',choices:[['Transport','TR','Fuel and vehicle'],['Shopping','SH','Store purchase'],['Other','OT','Something else']],selected:'Transport',remember:'Use Transport for future Shell purchases',evidence:'CHASE: Card purchase $47.32 at SHELL OIL 5742.'},
{id:'r3',merchant:'Unassigned merchant',initials:'?',amount:-19.42,when:'Jul 14 · 8:14 AM',account:'Chase Card •• 4471',reason:'Merchant name',type:'merchant',question:'Which merchant is this?',hint:'The source text suggests a local café, but the merchant name was incomplete.',choices:[['Corner Café','CC','Suggested match'],['Starbucks','SB','Known merchant'],['Keep unassigned','?','Review later']],selected:'Corner Café',remember:'Remember this merchant match for similar alerts',evidence:'CHASE: Purchase $19.42 at CRNR CAFE PLANO TX.'},
{id:'r4',merchant:'Card payment',initials:'CP',amount:-400,when:'Jul 15 · 1:16 PM',account:'Chase Checking → Amex',reason:'Spending effect',type:'source',question:'Should this affect spending?',hint:'Card payments move money between your own accounts and normally should not count as spending.',choices:[['Not spending','↔','Internal payment'],['Spending','−','Count as expense']],selected:'Not spending',remember:'Treat future card payments as money moved',evidence:'CHASE: Online payment $400.00 to AMEX ending 1002.'},
{id:'r5',merchant:'Whole Foods refund',initials:'WF',amount:38.61,when:'Jul 13 · 3:28 PM',account:'Chase Card •• 4471',reason:'Spending effect',type:'source',question:'How should this credit affect July?',hint:'A refund should reduce the category total rather than appear as income.',choices:[['Reduce spending','↘','Refund or reversal'],['Income','+','New money received']],selected:'Reduce spending',remember:'Treat Whole Foods credits as refunds',evidence:'CHASE: Credit $38.61 from WHOLE FOODS MKT.'},
{id:'r6',merchant:'Starbucks',initials:'SB',amount:-6.75,when:'Jul 12 · 8:05 AM',account:'Chase Card •• 4471',reason:'Possible duplicate',type:'source',question:'Are these two alerts the same purchase?',hint:'The amounts and times are close. Confirming prevents double-counting.',choices:[['Same purchase','1×','Keep one transaction'],['Two purchases','2×','Keep both']],selected:'Same purchase',remember:'',evidence:'Two alerts: STARBUCKS $6.75 at 8:05 AM and STARBUCKS $6.75 at 8:07 AM.'},
